commit to main

diff --git a/.eas/build/capacitor-ios.yml b/.eas/build/capacitor-ios.yml
--- a/.eas/build/capacitor-ios.yml
+++ b/.eas/build/capacitor-ios.yml
@@ -57,6 +57,99 @@ build:
           fi
           npx cap sync ios
     - run:
+        name: Ensure shared App scheme exists (required for xcodebuild/Fastlane)
+        command: |
+          SCHEME_DIR="ios/App/App.xcodeproj/xcshareddata/xcschemes"
+          mkdir -p "$SCHEME_DIR"
+          PBX="ios/App/App.xcodeproj/project.pbxproj"
+          # Extract App target BlueprintIdentifier (ID of PBXNativeTarget "App")
+          BLUEPRINT=$(sed -n 's/^[[:space:]]*\([A-Za-z0-9]*\)[[:space:]]*\/\* App \*\/ = {.*/\1/p' "$PBX" | head -1)
+          if [ -z "$BLUEPRINT" ]; then
+            echo "Could not find App target in $PBX"
+            exit 1
+          fi
+          echo "Using BlueprintIdentifier: $BLUEPRINT"
+          cat > "$SCHEME_DIR/App.xcscheme" << SCHEMEEOF
+          <?xml version="1.0" encoding="UTF-8"?>
+          <Scheme
+             LastUpgradeVersion = "1500"
+             version = "1.7">
+             <BuildAction
+                parallelizeBuildables = "YES"
+                buildImplicitDependencies = "YES">
+                <BuildActionEntries>
+                   <BuildActionEntry
+                      buildForTesting = "YES"
+                      buildForRunning = "YES"
+                      buildForProfiling = "YES"
+                      buildForArchiving = "YES"
+                      buildForAnalyzing = "YES">
+                      <BuildableReference
+                         BuildableIdentifier = "primary"
+                         BlueprintIdentifier = "$BLUEPRINT"
+                         BuildableName = "App.app"
+                         BlueprintName = "App"
+                         ReferencedContainer = "container:App.xcodeproj">
+                      </BuildableReference>
+                   </BuildActionEntry>
+                </BuildActionEntries>
+             </BuildAction>
+             <TestAction
+                buildConfiguration = "Debug"
+                selectedDebuggerIdentifier = "Xcode.DebuggerFoundation.Debugger.LLDB"
+                selectedLauncherIdentifier = "Xcode.DebuggerFoundation.Launcher.LLDB"
+                shouldUseLaunchSchemeArgsEnv = "YES"
+                shouldAutocreateTestPlan = "YES">
+             </TestAction>
+             <LaunchAction
+                buildConfiguration = "Debug"
+                selectedDebuggerIdentifier = "Xcode.DebuggerFoundation.Debugger.LLDB"
+                selectedLauncherIdentifier = "Xcode.DebuggerFoundation.Launcher.LLDB"
+                launchStyle = "0"
+                useCustomWorkingDirectory = "NO"
+                ignoresPersistentStateOnLaunch = "NO"
+                debugDocumentVersioning = "YES"
+                debugServiceExtension = "internal"
+                allowLocationSimulation = "YES">
+                <BuildableProductRunnable
+                   runnableDebuggingMode = "0">
+                   <BuildableReference
+                      BuildableIdentifier = "primary"
+                      BlueprintIdentifier = "$BLUEPRINT"
+                      BuildableName = "App.app"
+                      BlueprintName = "App"
+                      ReferencedContainer = "container:App.xcodeproj">
+                   </BuildableReference>
+                </BuildableProductRunnable>
+             </LaunchAction>
+             <ProfileAction
+                buildConfiguration = "Release"
+                shouldUseLaunchSchemeArgsEnv = "YES"
+                savedToolIdentifier = ""
+                useCustomWorkingDirectory = "NO"
+                debugDocumentVersioning = "YES">
+                <BuildableProductRunnable
+                   runnableDebuggingMode = "0">
+                   <BuildableReference
+                      BuildableIdentifier = "primary"
+                      BlueprintIdentifier = "$BLUEPRINT"
+                      BuildableName = "App.app"
+                      BlueprintName = "App"
+                      ReferencedContainer = "container:App.xcodeproj">
+                   </BuildableReference>
+                </BuildableProductRunnable>
+             </ProfileAction>
+             <AnalyzeAction
+                buildConfiguration = "Debug">
+             </AnalyzeAction>
+             <ArchiveAction
+                buildConfiguration = "Release"
+                revealArchiveInOrganizer = "YES">
+             </ArchiveAction>
+          </Scheme>
+          SCHEMEEOF
+          echo "Created $SCHEME_DIR/App.xcscheme"
+    - run:
         name: Remove Expo/RN again before pod install (third pass)
         command: |
           export NVM_DIR="$HOME/.nvm"
